name: Dev Deploy

on:
  workflow_call:
    inputs: 
      aws-access-key-id: 
        required: true 
        type: string
      aws-secret-access-key: 
        required: true 
        type: string 
      aws-region: 
        required: true 
        type: string 

jobs:
  build:
    environment: Dev
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install python dependencies
        run: pip install -r requirements.txt

      - name: Install python dev dependencies
        run: pip install --target ./src -r requirements-dev.txt

      - name: Install python infrastructure dependencies
        run: pip install -r requirements-infra.txt

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '16.3.0'

      - name: install aws cdk
        run: npm install -g aws-cdk


      - name: Configure AWS Credentials (Raw ACcount)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ inputs.aws-access-key-id }}
          aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
          aws-region: ${{ inputs.aws-region }}
